import Head from 'next/head';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../utils/requests';

export default function Home({ results }) {
  console.log(results + ' index.js')
  return (
    <div>
      <Head>
        <title>Hulu-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genere = context.query.genere;
  
  const request = await fetch(
    `https://api.themoviedb.org/3${requests[genere]?.url || requests.fetchActionMovies.url}`
  );

  const data = await request.json();

    return {
    props: {
      results: data.results,
    },
  };
}